<?php

namespace Application\Sonata\MediaBundle\Entity;

use AppBundle\Entity\FlatSale;
use AppBundle\Entity\FlatSaleHasPhotos;
use AppBundle\Entity\RoomHasPhotos;
use Sonata\MediaBundle\Entity\BaseMedia as BaseMedia;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References:
 * @link http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 */
class Media extends BaseMedia
{
    /**
     * @var int $id
     */
    protected $id;

    /*
     * @var RoomRent
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\RoomRent", inversedBy="room_photos")
     * @ORM\JoinColumns({
     *     @ORM\JoinColumn(name="room", referencedColumnName="id_room")
     * })
     *
    private $rooms_rental;*/

    /**
     * @var RoomHasPhotos
     ** @ORM\OneToMany(targetEntity="AppBundle\Entity\RoomsHasPhotos", mappedBy="photo", cascade={"all"})
     *
     */
    private $rooms_rental;

    /**
     * @var FlatSaleHasPhotos
     ** @ORM\OneToMany(targetEntity="AppBundle\Entity\FlatSaleHasPhotos", mappedBy="photo", cascade={"all"})
     *
     */
    private $flats_sale;

    /**
     * @var FlatRentHasPhotos
     ** @ORM\OneToMany(targetEntity="AppBundle\Entity\FlatRentHasPhotos", mappedBy="photo", cascade={"all"})
     *
     */
    private $flats_rental;

/*
 * @var FlatSale
 *
 * @ORM\ManyToOne(targetEntity="AppBundle\Entity\FlatSale", inversedBy="flat_photos")
 * @ORM\JoinColumns({
 *     @ORM\JoinColumn(name="flat_sale", referencedColumnName="id_flat_sale")
 * })
 *
    private $flats_sale;*/

    /**
     * Get id.
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return RoomHasPhotos
     */
    public function getRoomsRental()
    {
        return $this->rooms_rental;
    }

    /**
     * @param RoomHasPhotos $rooms_rental
     */
    public function setRoomsRental($rooms_rental)
    {
        $this->rooms_rental = $rooms_rental;
    }

    /**
     * @return FlatSaleHasPhotos
     */
    public function getFlatsSale()
    {
        return $this->flats_sale;
    }

    /**
     * @param FlatSale $flats_sale
     */
    public function setFlatsSale($flats_sale)
    {
        $this->flats_sale = $flats_sale;
    }

    /**
     * @return FlatRentHasPhotos
     */
    public function getFlatsRental()
    {
        return $this->flats_rental;
    }

    /**
     * @param FlatRentHasPhotos $flats_rental
     */
    public function setFlatsRental($flats_rental)
    {
        $this->flats_rental = $flats_rental;
    }


}
